twig:
    default_path: '%kernel.project_dir%/templates'
    form_themes:
        - 'form/custom_Types.html.twig'
        - 'form/fields.html.twig'
        - 'bootstrap_4_layout.html.twig'


    auto_reload: true

    globals:

