<?php

// This file was generated by running "composer dump-env prod"

return array (
  'APP_ENV' => 'prod',
  'APP_DEBUG' => 'false',
  'APP_SECRET' => 'ebba7465e79b447bf1737fc139c89e5a',
  'MAILER_DSN' => 'smtp://benjamin.voigt@vapita.de:Camilla%402323@vapita.de:25',
  'DATABASE_URL' => 'mysql://bvoigt:Camilla@2323@localhost:3306/vapita',
);
